spring.application.name=ShoppingBootApp

spring.datasource.url=jdbc:mysql://localhost:3306/shoppingdb
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=root67
=======
spring.datasource.password=12345
>>>>>>> feature/nay-bhone-khant

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false

# ==========================================
# Spring Mail Configuration (Gmail SMTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=naybhonekhant115@gmail.com
# Paste the 16-character App Password (without spaces)
spring.mail.password=dunihsmtdqrqzhwy

# SMTP Protocol Settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Optional: Print detailed mail logs in console during testing
spring.mail.properties.mail.debug=true